image: python:3.7

services:
  - postgres:9.6
  - redis:3.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: myproject

cache:
  key: "test"
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - test_functionality
  - pep8
  - test_notebooks

pep8:
  stage: pep8
  artifacts:
    when: on_failure
    paths:
      - flake8-report.txt
    expire_in: 1 week
  script:
    - flake8 --statistics --output-file flake8-report.txt

default_simulation:
  stage: test_functionality
  script:
    - python3 tests/performance.py

.test_notebook: &test_notebook
  stage: test_notebooks
  script:
    - cd examples
    - jupyter nbconvert --to script ${NOTEBOOK}.ipynb
    - ipython3 ${NOTEBOOK}.py
  artifacts:
    paths:
      - pics/${FIGURE}
    expire_in: 1 week

con_contact:
  variables:
    NOTEBOOK: con_contact
    FIGURE: Contagion_Contact_Tracing.png
  <<: *test_notebook

con_example:
  variables:
    NOTEBOOK: con_example
    FIGURE: none
  <<: *test_notebook

con_parameter_scan:
  variables:
    NOTEBOOK: con_parameter_scan
    FIGURE: Contagion_Contact_Rate_Scan.png
  <<: *test_notebook

con_distribution_comparison:
  variables:
    NOTEBOOK: con_distribution_comparison
    FIGURE: Contagion_Distribution.png
  <<: *test_notebook
