image: python:3.6

services:
  - postgres:9.6
  - redis:3.2

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POSTGRES_DB: myproject

cache:
  key: "test"
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

stages:
  - test_functionality
  - pep8
  - test_notebooks

pep8:
  stage: pep8
  artifacts:
    when: on_failure
    paths:
      - flake8-report.txt
  script:
    - flake8 --statistics --output-file flake8-report.txt
  allow_failure: true

default_simulation:
  stage: test_functionality
  script:
    - python3 tests/performance.py

.test_notebook: &test_notebook
  stage: test_notebooks
  script:
    - cd examples
    - jupyter nbconvert --to script ${NOTEBOOK}.ipynb
    - ipython3 ${NOTEBOOK}.py
  artifacts:
    paths:
      - pics/${FIGURE}

con_contact:
  variables:
    NOTEBOOK: con_contact
    FIGURE: Contagion_Contact_Tracing.png
  <<: *test_notebook

con_example:
  variables:
    NOTEBOOK: con_example
    FIGURE: none
  <<: *test_notebook

con_parameter_scan:
  variables:
    NOTEBOOK: con_parameter_scan
    FIGURE: Contagion_Contact_Rate_Scan.png
  <<: *test_notebook
